export function exportToCSV(data: Record<string, any>[], filename: string) {
  if (data.length === 0) return;
  const headers = Object.keys(data[0]);
  const csvContent = [
    headers.join(","),
    ...data.map((row) =>
      headers
        .map((h) => {
          const val = row[h] ?? "";
          const str = String(val).replace(/"/g, '""');
          return `"${str}"`;
        })
        .join(",")
    ),
  ].join("\n");

  downloadFile(csvContent, `${filename}.csv`, "text/csv");
}

export function exportToJSON(data: any, filename: string) {
  const jsonContent = JSON.stringify(data, null, 2);
  downloadFile(jsonContent, `${filename}.json`, "application/json");
}

export function exportToText(content: string, filename: string) {
  downloadFile(content, `${filename}.txt`, "text/plain");
}

export function exportToPDFText(sections: { title: string; content: string }[], filename: string) {
  // Generate a styled HTML document and trigger print/save as PDF
  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${filename}</title>
  <style>
    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 40px; color: #0D0D0D; line-height: 1.6; }
    h1 { color: #D4A017; border-bottom: 2px solid #D4A017; padding-bottom: 8px; font-size: 24px; }
    h2 { color: #333; margin-top: 24px; font-size: 18px; }
    .section { margin-bottom: 24px; }
    .content { background: #f9f9f7; padding: 16px; border-radius: 8px; border-left: 3px solid #D4A017; }
    .footer { margin-top: 40px; text-align: center; color: #6B7280; font-size: 12px; border-top: 1px solid #e5e5e5; padding-top: 16px; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 12px; font-weight: 600; }
    .high { background: #fde8e8; color: #b91c1c; }
    .medium { background: #fef3c7; color: #d97706; }
    .low { background: #d1fae5; color: #059669; }
    @media print { body { margin: 20px; } }
  </style>
</head>
<body>
  <h1>LitigeAI — ${filename}</h1>
  ${sections
    .map(
      (s) => `
    <div class="section">
      <h2>${s.title}</h2>
      <div class="content">${s.content}</div>
    </div>`
    )
    .join("")}
  <div class="footer">
    Generated by LitigeAI · ${new Date().toLocaleDateString()} · Confidential
  </div>
</body>
</html>`;

  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const win = window.open(url, "_blank");
  if (win) {
    win.onload = () => {
      win.print();
    };
  }
}

function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
